import './globals.css'

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import { TextHoverEffect } from '@/components/aceternity/text-hover'
import { Navbar } from '@/components/menu-navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Portfólio Wesley Ribas',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <div className="flex bg-slate-600 px-8 py-4">
          <div className="flex h-14 justify-center pl-2">
            <span className="font-r text-2xl">Wesley Ribas</span>
          </div>
          <Navbar className="top-4" />
        </div>
        {children}
      </body>
    </html>
  )
}
